# TCL File Generated by Component Editor 15.1
# Wed Mar 30 19:46:14 PDT 2016
# DO NOT MODIFY


# 
# ztachip "ztachip" v1.0
#  2016.03.30.19:46:14
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module ztachip
# 
set_module_property DESCRIPTION ""
set_module_property NAME ztachip
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ztachip
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bridge.vhd VHDL PATH bridge.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point hreset
# 
add_interface hreset reset end
set_interface_property hreset associatedClock hclock
set_interface_property hreset synchronousEdges DEASSERT
set_interface_property hreset ENABLED true
set_interface_property hreset EXPORT_OF ""
set_interface_property hreset PORT_NAME_MAP ""
set_interface_property hreset CMSIS_SVD_VARIABLES ""
set_interface_property hreset SVD_ADDRESS_GROUP ""

add_interface_port hreset hreset_in reset_n Input 1

# 
# connection point mreset
# 
add_interface mreset reset end
set_interface_property mreset associatedClock mclock
set_interface_property mreset synchronousEdges DEASSERT
set_interface_property mreset ENABLED true
set_interface_property mreset EXPORT_OF ""
set_interface_property mreset PORT_NAME_MAP ""
set_interface_property mreset CMSIS_SVD_VARIABLES ""
set_interface_property mreset SVD_ADDRESS_GROUP ""

add_interface_port mreset mreset_in reset_n Input 1

# 
# connection point preset
# 
add_interface preset reset end
set_interface_property preset associatedClock pclock
set_interface_property preset synchronousEdges DEASSERT
set_interface_property preset ENABLED true
set_interface_property preset EXPORT_OF ""
set_interface_property preset PORT_NAME_MAP ""
set_interface_property preset CMSIS_SVD_VARIABLES ""
set_interface_property preset SVD_ADDRESS_GROUP ""

add_interface_port preset preset_in reset_n Input 1

# 
# connection point dreset
# 
add_interface dreset reset end
set_interface_property dreset associatedClock dclock
set_interface_property dreset synchronousEdges DEASSERT
set_interface_property dreset ENABLED true
set_interface_property dreset EXPORT_OF ""
set_interface_property dreset PORT_NAME_MAP ""
set_interface_property dreset CMSIS_SVD_VARIABLES ""
set_interface_property dreset SVD_ADDRESS_GROUP ""

add_interface_port dreset dreset_in reset_n Input 1

# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock hclock
set_interface_property s0 associatedReset hreset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 2
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_chipselect chipselect Input 1
add_interface_port s0 avs_s0_waitrequest waitrequest Output 1
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_readdata readdata Output 32
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_address address Input 17
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point m0
# 
add_interface m0 avalon start
set_interface_property m0 addressUnits SYMBOLS
set_interface_property m0 associatedClock dclock
set_interface_property m0 associatedReset dreset
set_interface_property m0 bitsPerSymbol 8
set_interface_property m0 burstOnBurstBoundariesOnly true
set_interface_property m0 burstcountUnits WORDS
set_interface_property m0 doStreamReads false
set_interface_property m0 doStreamWrites false
set_interface_property m0 holdTime 0
set_interface_property m0 linewrapBursts false
set_interface_property m0 maximumPendingReadTransactions 64
set_interface_property m0 maximumPendingWriteTransactions 64
set_interface_property m0 readLatency 0
set_interface_property m0 readWaitTime 1
set_interface_property m0 setupTime 0
set_interface_property m0 timingUnits Cycles
set_interface_property m0 writeWaitTime 0
set_interface_property m0 ENABLED true
set_interface_property m0 EXPORT_OF ""
set_interface_property m0 PORT_NAME_MAP ""
set_interface_property m0 CMSIS_SVD_VARIABLES ""
set_interface_property m0 SVD_ADDRESS_GROUP ""

add_interface_port m0 avm_m0_address address Output 32
add_interface_port m0 avm_m0_burstcount burstcount Output 3
add_interface_port m0 avm_m0_read read Output 1
add_interface_port m0 avm_m0_readdata readdata Input 64
add_interface_port m0 avm_m0_readdatavalid readdatavalid Input 1
add_interface_port m0 avm_m0_waitrequest waitrequest Input 1
add_interface_port m0 avm_m0_write write Output 1
add_interface_port m0 avm_m0_writedata writedata Output 64
add_interface_port m0 avm_m0_byteenable byteenable Output 8
add_interface_port m0 avm_m0_writeresponsevalid writeresponsevalid Input 1
add_interface_port m0 avm_m0_response response Input 2


# 
# connection point m1
# 
add_interface m1 avalon start
set_interface_property m1 addressUnits SYMBOLS
set_interface_property m1 associatedClock dclock
set_interface_property m1 associatedReset dreset
set_interface_property m1 bitsPerSymbol 8
set_interface_property m1 burstOnBurstBoundariesOnly true
set_interface_property m1 burstcountUnits WORDS
set_interface_property m1 doStreamReads false
set_interface_property m1 doStreamWrites false
set_interface_property m1 holdTime 0
set_interface_property m1 linewrapBursts false
set_interface_property m1 maximumPendingReadTransactions 64
set_interface_property m1 maximumPendingWriteTransactions 64
set_interface_property m1 readLatency 0
set_interface_property m1 readWaitTime 1
set_interface_property m1 setupTime 0
set_interface_property m1 timingUnits Cycles
set_interface_property m1 writeWaitTime 0
set_interface_property m1 ENABLED true
set_interface_property m1 EXPORT_OF ""
set_interface_property m1 PORT_NAME_MAP ""
set_interface_property m1 CMSIS_SVD_VARIABLES ""
set_interface_property m1 SVD_ADDRESS_GROUP ""

add_interface_port m1 avm_m1_address address Output 32
add_interface_port m1 avm_m1_burstcount burstcount Output 3
add_interface_port m1 avm_m1_read read Output 1
add_interface_port m1 avm_m1_readdata readdata Input 64
add_interface_port m1 avm_m1_readdatavalid readdatavalid Input 1
add_interface_port m1 avm_m1_waitrequest waitrequest Input 1
add_interface_port m1 avm_m1_write write Output 1
add_interface_port m1 avm_m1_writedata writedata Output 64
add_interface_port m1 avm_m1_byteenable byteenable Output 8
add_interface_port m1 avm_m1_writeresponsevalid writeresponsevalid Input 1
add_interface_port m1 avm_m1_response response Input 2

# 
# connection point m2
# 
add_interface m2 avalon start
set_interface_property m2 addressUnits SYMBOLS
set_interface_property m2 associatedClock dclock
set_interface_property m2 associatedReset dreset
set_interface_property m2 bitsPerSymbol 8
set_interface_property m2 burstOnBurstBoundariesOnly true
set_interface_property m2 burstcountUnits WORDS
set_interface_property m2 doStreamReads false
set_interface_property m2 doStreamWrites false
set_interface_property m2 holdTime 0
set_interface_property m2 linewrapBursts false
set_interface_property m2 maximumPendingReadTransactions 64
set_interface_property m2 maximumPendingWriteTransactions 64
set_interface_property m2 readLatency 0
set_interface_property m2 readWaitTime 1
set_interface_property m2 setupTime 0
set_interface_property m2 timingUnits Cycles
set_interface_property m2 writeWaitTime 0
set_interface_property m2 ENABLED true
set_interface_property m2 EXPORT_OF ""
set_interface_property m2 PORT_NAME_MAP ""
set_interface_property m2 CMSIS_SVD_VARIABLES ""
set_interface_property m2 SVD_ADDRESS_GROUP ""

add_interface_port m2 avm_m2_address address Output 32
add_interface_port m2 avm_m2_burstcount burstcount Output 3
add_interface_port m2 avm_m2_read read Output 1
add_interface_port m2 avm_m2_readdata readdata Input 64
add_interface_port m2 avm_m2_readdatavalid readdatavalid Input 1
add_interface_port m2 avm_m2_waitrequest waitrequest Input 1
add_interface_port m2 avm_m2_write write Output 1
add_interface_port m2 avm_m2_writedata writedata Output 64
add_interface_port m2 avm_m2_byteenable byteenable Output 8
add_interface_port m2 avm_m2_writeresponsevalid writeresponsevalid Input 1
add_interface_port m2 avm_m2_response response Input 2


#
# hclock
#
add_interface hclock clock end
set_interface_property hclock clockRate 0
set_interface_property hclock ENABLED true
set_interface_property hclock EXPORT_OF ""
set_interface_property hclock PORT_NAME_MAP ""
set_interface_property hclock CMSIS_SVD_VARIABLES ""
set_interface_property hclock SVD_ADDRESS_GROUP ""

add_interface_port hclock hclock_in clk Input 1

# 
# connection mclock
# 
add_interface mclock clock end
set_interface_property mclock clockRate 0
set_interface_property mclock ENABLED true
set_interface_property mclock EXPORT_OF ""
set_interface_property mclock PORT_NAME_MAP ""
set_interface_property mclock CMSIS_SVD_VARIABLES ""
set_interface_property mclock SVD_ADDRESS_GROUP ""

add_interface_port mclock mclock_in clk Input 1

# 
# connection pclock
# 
add_interface pclock clock end
set_interface_property pclock clockRate 0
set_interface_property pclock ENABLED true
set_interface_property pclock EXPORT_OF ""
set_interface_property pclock PORT_NAME_MAP ""
set_interface_property pclock CMSIS_SVD_VARIABLES ""
set_interface_property pclock SVD_ADDRESS_GROUP ""

add_interface_port pclock pclock_in clk Input 1

# 
# connection dclock
# 
add_interface dclock clock end
set_interface_property dclock clockRate 0
set_interface_property dclock ENABLED true
set_interface_property dclock EXPORT_OF ""
set_interface_property dclock PORT_NAME_MAP ""
set_interface_property dclock CMSIS_SVD_VARIABLES ""
set_interface_property dclock SVD_ADDRESS_GROUP ""

add_interface_port dclock dclock_in clk Input 1


