#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : crossbar.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Jan 06 23:59:44 -0500 2023
# SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: crossbar.sh [-help]
# usage: crossbar.sh [-lib_map_path]
# usage: crossbar.sh [-noclean_files]
# usage: crossbar.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'crossbar.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm xlconstant_v1_1_7 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 smartconnect_v1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_22 axi_vip_v1_1_8 lib_pkg_v1_0_2 fifo_generator_v13_2_5 lib_fifo_v1_0_14 blk_mem_gen_v8_4_4 lib_bmg_v1_0_13 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_24 axi_vdma_v6_3_10)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "crossbar.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_1779_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_1779_psr0_0.vhd" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_1779_psr_aclk_0.vhd" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_1779_psr_aclk1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_1779_arsw_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_1779_rsw_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_1779_awsw_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_1779_wsw_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_1779_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ea34/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_1779_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_1779_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/8047/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_1779_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_1779_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_1779_sarn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_1779_srn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_1779_s01mmu_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_1779_s01tr_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_1779_s01sic_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_1779_s01a2s_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_1779_sarn_1.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_1779_srn_1.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_1779_sawn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_1779_swn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_1779_sbn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_1779_s02mmu_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_1779_s02tr_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_1779_s02sic_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_1779_s02a2s_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_1779_sarn_2.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_1779_srn_2.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_1779_s03mmu_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_1779_s03tr_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_32/sim/bd_1779_s03sic_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_33/sim/bd_1779_s03a2s_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_34/sim/bd_1779_sawn_1.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_35/sim/bd_1779_swn_1.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_36/sim/bd_1779_sbn_1.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_37/sim/bd_1779_s04mmu_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_38/sim/bd_1779_s04tr_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_39/sim/bd_1779_s04sic_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_40/sim/bd_1779_s04a2s_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_41/sim/bd_1779_sarn_3.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_42/sim/bd_1779_srn_3.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_43/sim/bd_1779_sawn_2.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_44/sim/bd_1779_swn_2.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_45/sim/bd_1779_sbn_2.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_46/sim/bd_1779_m00s2a_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_47/sim/bd_1779_m00arn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_48/sim/bd_1779_m00rn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_49/sim/bd_1779_m00awn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_50/sim/bd_1779_m00wn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_51/sim/bd_1779_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7bd7/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_52/sim/bd_1779_m00e_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_53/sim/bd_1779_m01s2a_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_54/sim/bd_1779_m01arn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_55/sim/bd_1779_m01rn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_56/sim/bd_1779_m01awn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_57/sim/bd_1779_m01wn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_58/sim/bd_1779_m01bn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_59/sim/bd_1779_m01e_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_60/sim/bd_1779_m02s2a_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_61/sim/bd_1779_m02arn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_62/sim/bd_1779_m02rn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_63/sim/bd_1779_m02awn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_64/sim/bd_1779_m02wn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_65/sim/bd_1779_m02bn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_66/sim/bd_1779_m02e_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_67/sim/bd_1779_m03s2a_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_68/sim/bd_1779_m03arn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_69/sim/bd_1779_m03rn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_70/sim/bd_1779_m03awn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_71/sim/bd_1779_m03wn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_72/sim/bd_1779_m03bn_0.sv" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/ip/ip_73/sim/bd_1779_m03e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/bd_0/sim/bd_1779.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_smartconnect_0_0/sim/crossbar_smartconnect_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/af67/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_24 $vhdlan_opts \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/4ab6/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_10 $vhdlan_opts \
    "$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/crossbar/ip/crossbar_axi_vdma_0_0/sim/crossbar_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../GHRD.gen/sources_1/bd/crossbar/ipshared/7860/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/crossbar/sim/crossbar.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.crossbar xil_defaultlib.glbl -o crossbar_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./crossbar_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./crossbar.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key crossbar_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc crossbar_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./crossbar.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: crossbar.sh [-help]\n\
Usage: crossbar.sh [-lib_map_path]\n\
Usage: crossbar.sh [-reset_run]\n\
Usage: crossbar.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
