name: Generate Toolchains

on:
  push:
    tags:
      - "*"
  
jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Add Release Note & Artifact'
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "CHANGELOG.md"           #artifacts: "Add path to release.tar.gz,foo/*.txt"